services:
  - type: web
    name: agentsphere
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npx prisma db push --accept-data-loss && npm run start
    envVars:
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_GENERATIVE_AI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false

